apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-spark
  labels:
    app: apache-spark
spec:
  replicas: 1
  selector:
     matchLabels:
       app: apache-spark
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: apache-spark
    spec:
      containers:
        - image: bitnami/spark
          imagePullPolicy: Always
          name: apache-spark
          env:
          - name: SPARK_MODE
            value: "master"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: apache-spark
  labels:
    name: apache-spark
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    name: apache-spark
