apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  selector:
     matchLabels:
       app: jupyter-notebook
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
       image: jupyter/datascience-notebook:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888
          command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    name: jupyter-notebook
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyter-notebook
