apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
     matchLabels:
       app: sonarqube
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - image: bitnami/sonarqube
          imagePullPolicy: Always
          name: sonarqube
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    name: sonarqube
spec:
  type: LoadBalancer
  ports:
    - port: 60
      targetPort: 6000
      protocol: TCP
      name: http
  selector:
    name: sonarqube
